### ISSUE TITLE
Deploy on Vercel

### ISSUE THREAD

**Issue by k2on** [intergalacticspacehighway/expo-trpc#5]
Has anyone been able to deploy an Expo Web with Turborepo on Vercel?

I keep getting this error when I build with `expo export -p web`

```
Error: Error fetching bundle for static rendering: 404 Not Found
--
12:20:59.159 | Error: Error fetching bundle for static rendering: 404 Not Found
12:20:59.159 | at requireFileContentsWithMetro (/vercel/path0/node_modules/@expo/cli/src/start/server/getStaticRenderFunctions.ts:197:11)
12:20:59.159 | at processTicksAndRejections (node:internal/process/task_queues:95:5)
12:20:59.159 | at Object.getStaticRenderFunctions (/vercel/path0/node_modules/@expo/cli/src/start/server/getStaticRenderFunctions.ts:213:45)
12:20:59.159 | at MetroBundlerDevServer.getStaticRenderFunctionAsync (/vercel/path0/node_modules/@expo/cli/src/start/server/metro/MetroBundlerDevServer.ts:187:7)
12:20:59.159 | at async Promise.all (index 1)
12:20:59.159 | at exportFromServerAsync (/vercel/path0/node_modules/@expo/cli/src/export/exportStaticAsync.ts:197:66)
12:20:59.159 | at Object.unstable_exportStaticAsync (/vercel/path0/node_modules/@expo/cli/src/export/exportStaticAsync.ts:88:12)
12:20:59.159 | at Object.exportAppAsync (/vercel/path0/node_modules/@expo/cli/src/export/exportApp.ts:171:7)
12:20:59.159 | at exportAsync (/vercel/path0/node_modules/@expo/cli/src/export/exportAsync.ts:18:3)
12:20:59.176 | Error: Command "expo export -p web" exited with 1
```

**Comment by k2on** [comment]
It was in the build script the whole time. I forgot the `EXPO_USE_METRO_WORKSPACE_ROOT` in

```
EXPO_USE_METRO_WORKSPACE_ROOT=1 npx expo export -p web --dump-sourcemap
```
